name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          git zip unzip wget \
          autoconf automake libtool libtool-bin pkg-config zlib1g-dev \
          libncurses-dev \
          cmake libffi-dev libssl-dev \
          build-essential ccache \
          m4

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK with Buildozer
      run: |
        yes | buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: prescription-finder-apk
        path: bin/*.apk
        retention-days: 30
